# Generated by Django 3.2.16 on 2022-11-13 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahasiswa', '0001_initial'),
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perwalian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=12)),
                ('mulai_tahun_ajaran', models.PositiveIntegerField()),
                ('akhir_tahun_ajaran', models.PositiveIntegerField()),
                ('tanggal_perwalian', models.DateField()),
                ('masalah', models.TextField(blank=True, null=True)),
                ('saran', models.TextField(blank=True, null=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perwalian_as_dosen', to='dosen.dosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perwalian_as_mhs', to='mahasiswa.mahasiswa')),
            ],
        ),
    ]
