# Generated by Django 3.2.16 on 2022-11-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mata_kuliah', '0001_initial'),
        ('perwalian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RencanaStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mata_kuliah.matakuliah')),
                ('perwalian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perwalian.perwalian')),
            ],
        ),
    ]
