# Generated by Django 3.2.16 on 2022-11-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=8)),
                ('nama_depan', models.CharField(max_length=152)),
                ('nama_belakang', models.CharField(max_length=152)),
                ('alamat', models.CharField(max_length=256)),
                ('tanggal_lahir', models.DateField(null=True)),
                ('angkatan', models.IntegerField()),
            ],
        ),
    ]
